import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./provider/theme-provider";
import TanstackProvider from "./provider/tanstack-query-provider";
import { Toaster } from "@/components/ui/toaster";
import Header from "@/containers/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="scroll-smooth antialiased" suppressHydrationWarning={true}>
      <body className={`${inter.className} flex min-h-screen flex-col`}>
        <ThemeProvider
          attribute='class'
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TanstackProvider>
            <Header />
            <main className="grow" >
              {children}
            </main>
            <Toaster />
          </TanstackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
